### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by 89z** [Carcraftz/TLS-Fingerprint-API#11]
I dont see any option to mimic Android. If it helps, I have the JA3 here:

~~~
769,49195-49196-52393-49199-49200-52392-158-159-49161-49162-49171-49172-51-57-156-157-47-53,65281-0-23-35-13-16-11-10,23,0
~~~

or I can convert it to `ClientHelloSpec` if thats better. This would be a useful addition, as the server `android.clients.google.com` rejects any request without the Android Client Hello.

**Comment by Carcraftz** [comment]
yeah you might want to add the android fingerprint to my fork of UTLS

and then make a PR here that checks for android useragents and uses the appropriate fingerprints

let me know if you have any questions!

**Comment by 89z** [comment]
> yeah you might want to add the android fingerprint to my fork of UTLS

https://github.com/Carcraftz/utls

is a fork of this:

https://github.com/Titanium-ctrl/utls

is a fork of this:

https://gitlab.com/yawning/utls

is a fork of this:

https://github.com/refraction-networking/utls

is a fork of this:

https://godocs.io/crypto/tls

sorry, but thats too many forks.

**Comment by Carcraftz** [comment]
Crypto/tls was forked by UTLS to allow tls fingerprinting mitigation

utls was forked by yawning to enable certificate compression

titanium-ctrl is the same thing as the Gitlab repo but on Github

My fork is there so I can add additional devices in the future


Beauty of open source.
