### ISSUE TITLE
You don't know what tls fingerprint is

### ISSUE THREAD

**Issue by frankwalter1301** [Carcraftz/TLS-Fingerprint-API#12]
Otherwise you wouldn't have made a script that changes the order of the http headers by advertising it with TlS fInGeRpRiNt!1!

**Comment by frankwalter1301** [comment]
Oh sorry I saw there is a fork of a tls library.

**Comment by Carcraftz** [comment]
Yes, this repo uses my fork of cclient, a library that modifies your TLS fingerprint. 

It also fixes header order, as you mentioned, but header order is not the only fingerprinting method it mitigates.
