### ISSUE TITLE
Windows security alert of Trojan Win32/Sabsik.FL.B!ml when running proxy.go

### ISSUE THREAD

**Issue by caldaryx** [Carcraftz/TLS-Fingerprint-API#17]
Could be a false positive but from googling it this could be something pretty nasty https://howtofix.guide/trojanwin32-sabsik-fl-bml/

It comes back every time proxy.go is initiated. If this is a false positive has anyone else experienced it?

located in AppData\Local\Temp\go-build#######

**Comment by bytixo** [comment]
https://go.dev/doc/faq#virus

**Comment by caldaryx** [comment]
Thanks for that, I will mark it as false positive. I had run a go script previously and had no issue that's why I posted this here.
