### ISSUE TITLE
WebSocket upgrader types issue

### ISSUE THREAD

**Issue by nicoandmee** [Carcraftz/TLS-Fingerprint-API#19]
I am a novice golang coder so excuse me if this is a dumb question. But I am trying to adapt this project to handle WebSocket connections. In particular, I want to make a WebSocket connection and use https://pkg.go.dev/github.com/gorilla/websocket to upgrade the initial request. 

Code that produces issue:
```go
connPub, err := upgrader.Upgrade(w, req, nethttp.Header(upgradeHeader))
```
![image](https://user-images.githubusercontent.com/6896234/172464514-a8cd4559-d053-40ee-9606-dab2f257b2e2.png)
![image](https://user-images.githubusercontent.com/6896234/172463274-3b81c540-fad4-47e0-a533-8c5d1152c852.png)

But I'm running into a typings issue shown above. I ran into a similar thing elsewhere but was able to handle it by casting/converting `req.Header` (of type `fhttp.Header`) to `nethttp.Header` (I imported the vanilla `net/http` as `nethttp`) by doing `nethttp.Header(req.Header)`. But here I'm not sure what to do since that approach won't work. Any advice on how to workaround this to get WebSocket upgrade working?

**Comment by bytixo** [comment]
My advice would be to fork the websocket package and replace all the net/http imports by the fhttp package

**Comment by nicoandmee** [comment]
@bytixo How would that help though? The issue is `upgrader.Upgrade()` wants a value of type `net/http` not `fhttp`.

**Comment by bytixo** [comment]
`upgrader.Upgrade()` accept a `"net/http".Request` only, but if you fork the gorilla/websocket package and replace all of his "net/http" imports by "github.com/Carcraftz/fhttp" it'll fix your issue.

That's how packages and module works in go.

**Comment by nicoandmee** [comment]
> `upgrader.Upgrade()` accept a `"net/http".Request` only, but if you fork the gorilla/websocket package and replace all of his "net/http" imports by "github.com/Carcraftz/fhttp" it'll fix your issue.
> 
> That's how packages and module works in go.

Thank you! I was able to get it to work
